### ISSUE TITLE
Need help in writing grok pattern 

### ISSUE THREAD

**Issue by chandanchilakamudi** [logstash-plugins/logstash-filter-elasticsearch#109]
I want to send log data in to elasticsearch to visualize the data through kibana.

please find the below sample log data.
02/08/2019 19:55:05 Reply from IP: bytes=32 time=677ms TTL=111 
02/08/2019 19:55:06 Request timed out.
02/08/2019 19:55:26 Reply from IP: Destination host unreachable.

Please help me  how to write 3 grok filter pattern to send data in to elastic search using logstash.

**Comment by n0othing** [comment]
Hi @chandanchilakamudi, could you please ask your question over at https://discuss.elastic.co/c/logstash? Issues filed in this repo are intended to discuss bugs or enhancements.

FWIW there's a bunch of really helpful guides/tutorials for getting started with grok (and Logstash in general) out on the web. I'd recommend checking out this blog[1].

[1] https://www.elastic.co/blog/a-practical-introduction-to-logstash
