### ISSUE TITLE
AWS ES Support

### ISSUE THREAD

**Issue by chrislujan** [logstash-plugins/logstash-filter-elasticsearch#113]
I saw this does not have aws es support (sigv4), so I wrote up a feature branch and have been using it for a short time now. How can I go about getting a branch pushed up here (access restricted repo) for testing and review?

**Comment by seanmcelroy** [comment]
@chrislujan that seems like it would be very useful -- what was the fate of your feature branch?

**Comment by chrislujan** [comment]
@seanmcelroy https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/116 I've been using this at work for a long time now, it works pretty well, I'd love it to get merged so I can stop installing it via the .gem file
