### ISSUE TITLE
Allow elasticsearch filter to use query DSL instead of query string

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-elasticsearch#13]
(This issue was originally filed by @kurtado at https://github.com/elastic/logstash-contrib/issues/122)

---

Instead of the Lucene query string, the filter should allow the user to specify an Elasticsearch query DSL JSON object. 

The config might look something like this:

```
elasticsearch {
  query_dsl => { ..... }
}
```

We'd need to decide what would happen if both query DSL and query string were included in the config...

**Comment by tcucchietti** [comment]
+1

**Comment by consulthys** [comment]
+1

**Comment by bertrandfalguiere** [comment]
+1 . It seems logical that using both query DSL and query string behaves exactly like a curl query using both DSL and string, right (query string prevails)? It's more consistent with the elasticsearch "non-plugin" behaviour.
I think that if someone want both the behaviour, they just use two instances of the plugin of use a more complex query DSL.

**Comment by gingerwizard** [comment]
https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/42

**Comment by ctindel** [comment]
@jordansissel I think you can close this now that PR 42 came in

**Comment by jordansissel** [comment]
@ctindel good call; thanks!

FIxed by #42/#53
