### ISSUE TITLE
Specifying multiple indices

### ISSUE THREAD

**Issue by madmax76** [logstash-plugins/logstash-filter-elasticsearch#138]
- Version: 7.8.1
- Operating System: Ubuntu 18.04.4 LTS 
- Config File:
index => [ "indexname", "otherIndexname" ]
- Error:
[ERROR] 2020-08-08 09:50:00.921 [Converge PipelineAction::Create<main>] elasticsearch - Invalid setting for elasticsearch filter plugin:

  filter {
    elasticsearch {
      # This setting must be a string
      # Expected string, got ["index_%{year}-%{month}", "index_%{year_prev}-%{month_prev}"]
      index => ["index_%{year}-%{month}", "index_%{year_prev}-%{month_prev}"]
      ...
    }
  }

We want to make searching in multiple indices possible, according to the documentation this is to be configured as a string in a comma-delimited list. According to the documentation a list is specified as ["asdsa","dfsdfds"], the configuration seems to be not accepted. Trying some other interpretations of the documents are:

- index => "indexname", "otherIndexname"
- index => "indexname, otherIndexname"
- index => { "indexname", "otherIndexname" }

What would be the syntax?

**Comment by T7life** [comment]
index => "indexname","otherIndexname"
there is no "space" prebehind comma

**Comment by madmax76** [comment]
> index => "indexname,otherIndexname" there is no "space" behind comma

Thank you @T7life.
