### ISSUE TITLE
Allow elasticsearch filter to specify index

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-elasticsearch#14]
(This issue was originally filed by @kurtado at https://github.com/elastic/logstash-contrib/issues/95)

---

Currently, the only configuration options are fields, host, query and sort. As far as I can tell, it is not possible to specify the index in a query string.

**Comment by tcucchietti** [comment]
+1

**Comment by psaiz** [comment]
+1

**Comment by colinsanders** [comment]
+1

**Comment by nzlosh** [comment]
Hi @jordansissel,

From what I've read on the issue, adding index support to the pluggin is technically possible but deemed undesirable because an empty string as a default (meaning all indexes) would be confusing for ES users.

Is that still the status quo?

**Comment by jordansissel** [comment]
@nzlosh I'm open to adding index support. If we document clearly the default behavior (and perhaps any warnings that are necessary), I think this will be ok.

I will certainly be happy to merge a PR for this feature with CLA signed, having tests, a backwards-compatible default, and suiting the requested behavior folks are asking for - Happy to help provide review/guidance on such a thing as it progresses.

**Comment by juerkan** [comment]
+1

**Comment by tornis** [comment]
+1

**Comment by roji** [comment]
+1

**Comment by hadiartik** [comment]
+1
without this capability I am having many sort related errors due to missing fields
Also, having search against specific index will be very useful

**Comment by teebu** [comment]
any update on this?

**Comment by xdzhou12** [comment]
+1

**Comment by consulthys** [comment]
I've created a new PR for this https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/34

**Comment by purbon** [comment]
got this change merged and published recently, closing this issue.

**Comment by consulthys** [comment]
Thanks!

**Comment by PhaedrusTheGreek** [comment]
As a workaround, you should be able to specify the Index in the query string, however it would lack efficiency since every index is queried.

```
_index:.my_index AND blah blah
```
