### ISSUE TITLE
Add `x-elastic-product-origin` header to all places that make requests to Elasticsearch

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-filter-elasticsearch#180]
The Logstash Elasticsearch filter plugin makes HTTP requests to the following Elasticsearch endpoints:

```
GET /
HEAD /
GET /_search
```

Each of these calls should include the `x-elastic-product-origin` header to the HTTP request made to Elasticsearch

**Comment by robbavey** [comment]
Updated to correct the header name to x-elastic-product-origin

**Comment by donoghuc** [comment]
Publish build https://github.com/logstash-plugins/publisher/actions/runs/12241674451
Shipped in [3.16.2](https://rubygems.org/gems/logstash-filter-elasticsearch/versions/3.16.2)
