### ISSUE TITLE
Do not log the full event if previous event is not found

### ISSUE THREAD

**Issue by boubou191911** [logstash-plugins/logstash-filter-elasticsearch#22]
Hello,

I am using the elasticsearch filter to search for previous events.
In my use case it happens often that there is no previous event and it is normal.

But with the current logger.warn instruction logging the full event object, the log files are becoming very big very quickly.

My suggestion would be to remove the event from the logger.warn instruction; maybe to add it at info level instead of warning.

**Comment by hadiartik** [comment]
+1

**Comment by muaazsaleem** [comment]
+1

**Comment by webmat** [comment]
Sorry for the delay in getting to this.

My understanding is that this is no longer an issue. Currently the plugin logs an error with the full search only if there's an actual exception (e.g. unable to connect), but it does not if the search simply yields no results.

In other words, this raises an exception, adds the failure tag and logs a warning (assuming lolcathost does not resolve ;-) ):

```
elasticsearch {
  hosts => [ "lolcathost:9200" ]
  query => "valid search"
  fields => { "message" => "prev.message" }
}
```

Whereas this search finds nothing, and gets skipped silently:

```
elasticsearch {
  hosts => [ "localhost:9200" ]
  query => "bad search"
  fields => { "message" => "prev.message" }
}
```

Please reopen if I misunderstood, and if you still feel that the logs are too noisy in your situation.
