### ISSUE TITLE
Setting a custom port using host:port is not working 

### ISSUE THREAD

**Issue by jakommo** [logstash-plugins/logstash-filter-elasticsearch#24]
Currently the documentation is not clear on how to set a custom port, as there is no `port =>` setting available.
Setting `hosts =>["localhost:9202"]` results in `the scheme https does not accept registry part: localhost:9202:9200 (or bad hostname?)`.

Using `hosts =>["http://localhost:9202"]` works.

**Comment by suyograo** [comment]
I think the bug is that we should support `hosts =>["localhost:9202"]` which is consistent with ES output plugin. `hosts =>["http://localhost:9202"]` is not correct and should be rejected.

**Comment by JacquotP** [comment]
Hello,

After reviewing connexion source code filter configuration, I think that the error came from using ssl tag. 
This one make change how the variable 'hosts' is managed (from URI field to hash table field). 

I will try to pull the solutions I have managed, but I do not know how to run unitary test.

**Comment by webmat** [comment]
Sorry for the delay.

I understand that this problem has been resolved by fixing the `hosts` array vs the `ssl` option?

I will accordingly close this issue. Please reopen if I misunderstood and you're still experiencing a problem.
