### ISSUE TITLE
Support %{name} in fields

### ISSUE THREAD

**Issue by sathibault** [logstash-plugins/logstash-filter-elasticsearch#27]
Dynamic field names could be supported with:

```
event[event.sprintf(new)] = results['hits']['hits'][0]['_source'][event.sprintf(old)]
```

**Comment by sathibault** [comment]
We've moved away from using ELK.

**Comment by webmat** [comment]
Sorry to hear that.

Anybody else finding this that really needs this, make yourselves heard. Closing for now.
