### ISSUE TITLE
fail to query elasticsearch for previous event

### ISSUE THREAD

**Issue by linhntt41** [logstash-plugins/logstash-filter-elasticsearch#28]
Hi all,
I'm using logstash 2.3, elasticsearch 2.3
I want to retrieve events in elasticsearch status:in and username but error.
this my file log: dur.log
2016-05-13 14:15:00 usera in
2016-05-13 14:16:00 usera out
this my config: test.conf
input{
        file{
                path =>"/opt/dur.log"
        }
}
filter{
        grok {
                match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{USERNAME:username} %{WORD:status}"}
            }
        if [status] == "in" {
           mutate {
              rename => {"timestamp" => "started"}
             }
           date {
           match =>["started","yyyy-MM-dd HH:mm:ss"]
           target => "[started]"
         }
     }

        if [status] == "out" {
          mutate {
              rename => {"timestamp" => "ended"}
             }
           date {
           match =>["ended","yyyy-MM-dd HH:mm:ss"]
           target => "[ended]"
         }
        }

        if [status] == "out"{
          elasticsearch {
              hosts => ["localhost:9200"]
              query => 'status:in AND username:"%{[username]}"'
              fields => ["started","ended"]
         }
}
}
output {
        stdout { codec => rubydebug}
        elasticsearch { hosts => ["localhost:9200"]
                         index => "dur-%{+YYYY.MM.dd}"}
}

Failed to query elasticsearch for previous event {:query=>"status:in AND username:\"usera\"", :event=>#<LogStash::Event:0x120f088f @metadata_accessors=#<LogStash::Util::Accessors:0x179c88db 
Can you help me? Thanks

**Comment by untergeek** [comment]
Hi @linhntt41 

Usage questions should be directed to our discussion forums at https://discuss.elastic.co/c/logstash

Github issues are reserved for bug reports and feature requests.
