### ISSUE TITLE
Brackets missing in the plugin documentation

### ISSUE THREAD

**Issue by pwiatrowski** [logstash-plugins/logstash-filter-elasticsearch#30]
Hi,

I think there are brackets missing in the plugin documentation:

> 
if [type] == "end" {
   elasticsearch {
      hosts => ["es-server"]
      query => "type:start AND operation:%{[opid]}"
      fields => **[** ["@timestamp", "started"] **]**
   }

Cheers!

**Comment by andrewsh82** [comment]
yes wasted the whole day on this :( Please change the docs

**Comment by jehuty0shift** [comment]
Since the documentation is generated from Code, i fixed it in #31 . Indeed, it was incorrect (lost a lot of time from that too).
