### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by sechacking** [logstash-plugins/logstash-filter-elasticsearch#50]
user like this

```
       grok {
          match => ["message","\s*\"(?<clientip>(.*?)?)\"\s+(.*)\s+\"(?<username>(.*?)?)\"\s+\"(?<usertype>(\S+)?)\""]
        }

elasticsearch{
     hosts=>["172.17.32.3:9200/sex_dic/sex/"]  
     query=>"username:%{username}"
     sort=>"_id:desc"
  }
```

i can not get want result...

i want search elasticsearch to remove uniq my data.To prevent repeated write data

so how can i?

**Comment by webmat** [comment]
Sorry for the delay.

Can you give me more details on what you're trying to accomplish? Or were you successful in doing what you wanted?

**Comment by webmat** [comment]
Closing this. Let us know or reopen if this is still an issue for you.
