### ISSUE TITLE
SSL is not working with the filter

### ISSUE THREAD

**Issue by ctindel** [logstash-plugins/logstash-filter-elasticsearch#58]
I'm trying to use the elastic cloud as my filter source.  I have a config like:

filter {
  elasticsearch {
    hosts => ["https://FOUND_SERVER.us-east-1.aws.found.io:9243"]
    ssl => true
    user => "elastic"
    password => "changeme"
  }
}

This doesn't work.  I tried also uninstalling the elasticsearch input plugin, which was pinning elasticsearch ruby client library to 1.0 so that installing the elasticsearch filter would install the 5.0 version of the ruby client library, but it didn't change anything.

Using http and ssl => false and port 9200 works fine for accessing the cluster so it does appear to be some sort of bug in the filter code.

**Comment by jsvd** [comment]
can you confirm that the host you are using in the hosts url contains underscores?

**Comment by ctindel** [comment]
No underscores it was an elastic cloud server.

**Comment by jsvd** [comment]
😞  there are many things wrong with the uri handling of this plugin when ssl joins the picture, I keep finding lose ends when trying to fix this. thanks @ctindel

**Comment by ctindel** [comment]
It should be very easy to reproduce. Why is the uri handing different than the elasticsearch output plugin? Just make them use the same code?

**Comment by jsvd** [comment]
these two plugins have always had very different development cycles. the es output moves a much faster speed and no longer uses the elasticsearch-ruby client, while the filter has been mostly neglected and on a best effort maintenance mode (this plugin isn't included by default in logstash packages).
There is some work done on the idea of moving all similar plugins to one repository so they can share code more easily, for example, https://github.com/logstash-plugins/logstash-integration-elasticsearch/, but it is currently stalled afaik.

**Comment by ctindel** [comment]
@jsvd Yeah it just seems strange that a plugin that talks to our own product is not a default plugin and has a totally separate (and neglected) code base.  Would be nice to have it all unified!
