### ISSUE TITLE
Correlation is not working in  logstash filter elasticsearch 

### ISSUE THREAD

**Issue by ganesh2303** [logstash-plugins/logstash-filter-elasticsearch#63]
Hi, 
I'm using new version of logstash(5.2.0) and i'm facing correlation issue in that. Kinldy find the below detail of my issue,

Actually im trying to move some fields from one index 1 to another index 2.
 Already i processed the index 1 data  and written the elasticsearch condition in index 2 to fetch the value from index. Please find the elasticsearch query below

```
elasticsearch {
				query_template => "/template.json"
			  					
		               }
```
template.json

```
{
    "query": {
      "query_string": {
       "query": "type:gvsh_reqold AND dlr_dlrCode:%{dlr_dlrCode} AND getVehicle_VIN:%{vehicle_vehicleID}"
      }
    },
   "fields": ["vehicle_SSC","vehicle_SSC"]
 }
```

Help me to resolve the issue as soon as possible and kindly let know my code is right or wrong.

Sometime getting this error,
`[2017-02-21T05:02:29,854][WARN ][logstash.filters.elasticsearch] Failed to query elasticsearch for previous event {:index=>"", :query=>{"query"=>{"query_string"=>{"query"=>"type:gvsh_reqold AND dlr_dlrCode:04136 AND getVehicle_VIN:JTDKN3DU9F0470982"}}, "fields"=>["vehicle_SSC", "vehicle_SSC"]}, :event=>2017-02-21T13:02:19.159Z`

**Comment by ganesh2303** [comment]
Anyone help to resolve this issue to come of this it.

**Comment by Nanjou-IT** [comment]
@ganesh2303 Hi, don't you miss some fields in your elasticsearch filter ? 
Such as : 
hosts => "localhost:9200"
index => "yourIndex"

Did you try to execute your query using command line directly on your Index?

**Comment by ganesh2303** [comment]
@Nanjou-IT  
I tried as you mentioned above scenario even though its reproducing same result  which i got early, but i fetching data in kibana console. Please find the below image,
![image](https://cloud.githubusercontent.com/assets/1695045/23457865/82ce9ad6-fe2e-11e6-9da4-e19a4f7c5a28.png)

**Comment by Nanjou-IT** [comment]
@ganesh2303 Ok and if you try the following configuration ?
```
elasticsearch {
  hosts => "localhost:9200"
  index => "yourIndex"
  query => "type:gvsh_reqold AND dlr_dlrCode:%{dlr_dlrCode} AND getVehicle_VIN:%{vehicle_vehicleID}"
  fields => { "vehicle_SSC" => "vehicle_SSC" }	  					
}
```

**Comment by ganesh2303** [comment]
@Nanjou-IT 
```
elasticsearch {
				
				hosts => ["localhost:9200"]
				index => "logstash-dd.getvehicleservicehistory"
			    query => "type:gvsh_reqold AND dlr_dlrCode:%{dlr_dlrCode} AND getVehicle_VIN:%{getVehicle_VIN}"			  
			    fields => [
			            "vehicle_SSC","vehicle_SSC"						
			            ]
					
		               }

```
this is code im using when i try this im getting following error,

```
[2017-03-01T03:25:41,865][INFO ][logstash.filters.elasticsearch] Querying elasticsearch for lookup {:params=>{:index=>"logstash-dd.getvehicleservicehistory", :q=>"type:gvsh_reqold AND dlr_dlrCode:04136 AND getVehicle_VIN:xxxxx", :size=>1, :sort=>"@timestamp:desc"}}
[2017-03-01T03:25:41,908][WARN ][logstash.filters.elasticsearch] Failed to query elasticsearch for previous event {:index=>"logstash-dd.getvehicleservicehistory", :query=>"type:gvsh_reqold AND dlr_dlrCode:04136 AND getVehicle_VIN:xxxxxx", :event=>2017-03-01T11:25:31.425Z
```

**Comment by ganesh2303** [comment]
@Nanjou-IT 

instead of using above config if i used this im not getting any error and field is not creating

```
elasticsearch {
				query_template => "/template.json"
			  					
		               }
```
template.json

```
{
    "query": {
      "query_string": {
       "query": "type:gvsh_reqold AND dlr_dlrCode:%{dlr_dlrCode} AND getVehicle_VIN:%{vehicle_vehicleID}"
      }
    },
   "fields": ["vehicle_SSC","vehicle_SSC"]
 }
```
