### ISSUE TITLE
use event value for index name

### ISSUE THREAD

**Issue by jdnn** [logstash-plugins/logstash-filter-elasticsearch#68]
Hi,

I'm trying to supply an event variable/field in the index name, such as:
      elasticsearch {
        hosts => ["localhost:9200"]
        index => "%{[@metadata][myindex]}"
        query => "..."
        fields => "..." }

But this fails with:
[logstash.filters.elasticsearch] Failed to query elasticsearch for previous event {:index=>"%{[@metadata][myindex]}", :query=>... "index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"%{[@metadata][myindex]}....

Tried different quoting and syntax for referencing the myindex field, but it never got resolved to its value. And it's overkill to search _all indices when the correct index would be known in the logstash script based on input data. 
Is there some way to achieve that?

This is with logstash 5.2.1 / logstash-filter-elasticsearch 3.1.3 on Linux

**Comment by jordansissel** [comment]
I think what is happening is that your event has no field `[@metadata][myindex]`. The way field formatting works is that if the field doesn't exist, logstash leaves the unformatted value, which means if your even has no `myfield` in `@metadata`, then what you showed is what I would expect to happen.

Are you certain that your events have a `[@metadata][myindex]` field?

**Comment by jordansissel** [comment]
Ignore my previous comment, I was wrong.

Looking at the code, this filter does not support formatting on the `index` setting. The value is used as-is from the configuration without  modification (https://github.com/logstash-plugins/logstash-filter-elasticsearch/blob/master/lib/logstash/filters/elasticsearch.rb#L151)

Making the `index` setting support field formatting will require code changes. I support the idea of allowing it.

**Comment by jdnn** [comment]
Yes, [@metadata][myindex] exists and has a value, I use it in the elasticsearch output plugin in the same way to specify the index, and there it works fine. 
Would be nice if this could be added to the filter plugin, too.

**Comment by okazymyrov** [comment]
Maybe it would be useful for someone. The following configuration doesn't work:
```
           hosts => ["127.0.0.1:9200"]
           index => "%{index}-*"
```

However, one can specify indexes in hosts (this works as expected):
`hosts => ["127.0.0.1:9200/%{index}-*/"]`

I have found a workaround on http://teknosrc.com/query-elasticsearch-cluster-filter-section-when-using-logstash/.

**Comment by okazymyrov** [comment]
+1

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/75 resolves this.

**Comment by JacqueCC** [comment]
Have you guys found a solution for this?
I am facing the same problem.
I add the value of endpoint field to [@metadata][myindex] in the filter:
```
 mutate { add_field => { "[@metadata][myindex]" => "%{endpoint}" } }
 mutate { remove_field => ["endpoint"] }
```
in the output I have done like this:
```
output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    codec => json
    manage_template => false
    hosts => [ "localhost:9200" ]
    user => "elastic"
    password => "changeme"
    index => "%{[@metadata][myindex]}"
    document_type => "ObjectEvent"
    document_id => "%{epc}"
  }
}
```
An index %{[@metadata][myindex]} has been created, but I need the value of %{[@metadata][myindex]}. Do you know if this is possible?

**Comment by JacqueCC** [comment]
It works now.

**Comment by JacqueCC** [comment]
Hi @sivaterli I've put an if condition before the elasticsearch output plugin to the variable [@metadata][myindex]. If this variable exists, then the elasticsearch output plugin is executed. It helps not create an index with the variable name if a value was not assigned to this variable yet.
