### ISSUE TITLE
Filter always returns true, disregarding actual results found

### ISSUE THREAD

**Issue by bperian** [logstash-plugins/logstash-filter-elasticsearch#93]
I was testing the filter on 6.2 and it was always tagging or trying to add fields even if no match was being found. Also this was sometime causing cannot convert nil to string errors in the logs because even though the filter was returning true there was no event attached as result. 

Suggested fix:  https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/92

I tested the suggested change and it works properly

**Comment by webmat** [comment]
Closing. Version 3.3.1 is published and fixes this.
