### ISSUE TITLE
Feature request: support PKI based authentication to ES

### ISSUE THREAD

**Issue by nick-george** [logstash-plugins/logstash-filter-elasticsearch#94]
The logstash-output-elasticsearch plugin supports authenticating to ES via PKI, that is, having the option to specify a TLS keystore (client-side cert) to use when connecting. 

It would be great if this plugin did too. Could the code for SSL be taken straight from the output plugin? 

Regards, 
Nick

**Comment by webmat** [comment]
This is a good suggestion, thanks. An overhaul of the 3 ElasticSearch plugins is coming up, and this will most likely be part of it.

**Comment by plipka77** [comment]
@webmat Is there any update on this? Unless I'm missing something, there is no way with the current set-up to connect to an Elasticsearch cluster with client authentication required with this plugin.
